[package]
name = "player"
version = "0.1.0"
edition = "2021"

[dependencies]
ytdlp_bindings = "*"
directories = "*"
regex = "*"
hashbrown = { version = "0.15.2", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive"] }
ron = "*"
colored = "*"
rusqlite = { version = "0.33.0", features = ["bundled"] }
